name: BTC Bot v2

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: List Files
        run: ls -la

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Bot Script
        run: python trading_bot.py

      - name: Show data.json
        run: cat data.json

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update BTC price"
            git push
          fi
