name: BTC Bot v2

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v3

      - name: Step 2 - Show Files
        run: ls -la

      - name: Step 3 - Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Step 4 - Install
        run: pip install -r requirements.txt

      - name: Step 5 - Run Bot
        run: python trading_bot.py

      - name: Step 6 - Show data
        run: cat data.json

      - name: Step 7 - Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update BTC price"
            git push
          fi
